### ISSUE TITLE
Exception when alpacka-backtrader-api client is connected

### ISSUE THREAD

**Issue by cloud-rocket** [camelpac/alpaca-proxy-agent#17]
```
2022-11-03 19:22:15,758 root Alpaca Proxy Agent v1.0.1
2022-11-03 19:22:15,758 root Using the Alpaca Websocket
2022-11-03 19:22:15,758 root Connecting to the paper account endpoint
2022-11-03 19:22:15,758 root Using the free subscription plan(iex)
2022-11-03 19:22:42,767 root Subscribing to: {'quotes': ['META']}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 50, in consumer_thread
    subscribe(channels)
  File "main.py", line 56, in subscribe
    conn.subscribe_trades(on_message, *channels['trades'])
KeyError: 'trades'

```

Any idea?

**Comment by kang205** [comment]
+1
