### ISSUE TITLE
subscription for more than 1 data channel can fail

### ISSUE THREAD

**Issue by KlausGlueckert** [camelpac/alpaca-proxy-agent#5]
In this case I am subscribing to 'alpacadatav1/AM.TSLA' and then 'alpacadatav1/AM.SPY.

Appereantly you ````await conn.unsubscribe(previous_channels)```` when adding additional subscriptions and then re-subscribe.
This process doesnt work and fails in the trade api part, because the [self._ws part is None](https://github.com/alpacahq/alpaca-trade-api-python/blob/788f03539d1a7930df89408bfc217e82d588e026/alpaca_trade_api/stream2.py#L135) 

````
2021-02-01 01:27:10,493 root Alpaca Proxy Agent v0.5.5
2021-02-01 01:27:10,493 root Using the Alpaca Websocket
< {'action': 'authenticate', 'data': {'key_id': 'PKMIAA7DFADUGOKNIGUR', 'secret_key': '98xk2nDUq6QswX9fAuN3Mj4ZLLUI7ptFrVCzTCtc'}}
< {'action': 'listen', 'data': {'streams': ['alpacadatav1/AM.TSLA']}}
previous channels []
new_channels ['alpacadatav1/AM.TSLA']
< {'action': 'authenticate', 'data': {'key_id': 'PKMIAA7DFADUGOKNIGUR', 'secret_key': '98xk2nDUq6QswX9fAuN3Mj4ZLLUI7ptFrVCzTCtc'}}
< {'action': 'listen', 'data': {'streams': ['alpacadatav1/AM.SPY']}}
previous channels ['alpacadatav1/AM.TSLA']
new_channels ['alpacadatav1/AM.SPY']
Traceback (most recent call last):
  File "main.py", line 169, in serve
    await conn.unsubscribe(previous_channels)
  File "/usr/local/lib/python3.6/site-packages/alpaca_trade_api/stream2.py", line 278, in unsubscribe
    await self.data_ws.unsubscribe(data_channels)
  File "/usr/local/lib/python3.6/site-packages/alpaca_trade_api/stream2.py", line 121, in unsubscribe
    await self._ws.send(json.dumps({
AttributeError: 'NoneType' object has no attribute 'send'

Done
2021-02-01 01:28:18,987 root connected to: wss://data.alpaca.markets/stream
````

**Comment by camelpac** [comment]
Hi, there's a new release for this project.
if this is still an issue, please let me know
